before_script:
  - yarn install

matrix:
  include:
    - language: node_js
      node_js: 8
      env: LANE='node'
      cache:
        yarn: true
      script:
        - ./.travis/travis-checks-js.sh
