version: 2.1

commands:
  yarn-install:
    steps:
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Cache
          key: yarn-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  react-native-install:
    steps:
    - run:
        name: Install command line tools
        command: |
          sudo npm install -g react-native-cli
  build-android:
    steps:
      - run:
          name: Change initial HTML file
          command: |
            cp ./bin/tmp/initial-device-tests-html.js ./src/app/initial-html.js
      - run:
          name: Bundle Debug android
          command: |
            mkdir -p android/app/src/main/assets
            react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - run:
          name: Gradle assemble debug android apk
          command: |
            cd android
            ./gradlew clean
            ./gradlew assembleDebug
  build-ios:
    steps:
    - run:
        name: Change initial HTML file
        command: |
          cp ./bin/tmp/initial-device-tests-html.js ./src/app/initial-html.js
    - run:
        name: Bundle iOS
        command: |
          react-native bundle --reset-cache --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'
    - run:
        name: Generate .app file
        command:  |
          react-native run-ios --configuration Release

jobs:
  checks:
    parameters:
      platform:
        type: string
        default: ""
      check-tests:
        type: boolean
        default: false
      check-correctness:
        type: boolean
        default: false
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Checkout Gutenberg
          command: |
            git submodule init
            git submodule update --recursive
      - yarn-install
      - run:
          name: Set Environment Variables
          command: |
            echo 'export CHECK_CORRECTNESS=<<parameters.check-correctness>>' >> $BASH_ENV
            echo 'export CHECK_TESTS=<<parameters.check-tests>>' >> $BASH_ENV
            echo 'export TEST_RN_PLATFORM=<<parameters.platform>>' >> $BASH_ENV
      - run:
          name: Run Checks
          command: bin/ci-checks-js.sh
  android-device-checks:
    docker:
    - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run:
          name: Checkout Gutenberg
          command: |
            git submodule init
            git submodule update --recursive
      - yarn-install
      - react-native-install
      - run:
          name: Set Environment Variables
          command: |
            echo 'export TEST_RN_PLATFORM=android' >> $BASH_ENV
            echo 'export TEST_ENV=sauce' >> $BASH_ENV
      - build-android
      - run:
          name: Upload apk to sauce labs
          command: |
            curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/automattic/Gutenberg.apk?overwrite=true --data-binary @./android/app/build/outputs/apk/debug/app-debug.apk
      - run:
          name: Run Device Tests
          command: yarn device-tests
  ios-device-checks:
    macos:
      xcode: "10.0"
    steps:
    - checkout
    - run:
        name: Checkout Gutenberg
        command: |
          git submodule init
          git submodule update --recursive
    - yarn-install
    - react-native-install
    - run: |
        sudo chown -R $USER:$GROUP ~/.config
    - run:
        name: Set Environment Variables
        command: |
          echo 'export TEST_RN_PLATFORM=ios' >> $BASH_ENV
          echo 'export TEST_ENV=sauce' >> $BASH_ENV
    - run:
        name: Yarn preios
        command: yarn preios
    - build-ios
    - run:
        name: Zip up .app file
        command: |
          cd ./ios/build/Build/Products/Release-iphonesimulator/
          zip -r ./Gutenberg.app.zip ./gutenberg.app
          mv ./Gutenberg.app.zip ../../../../../Gutenberg.app.zip
          cd ../../../../../
    - run:
        name: Upload apk to sauce labs
        command: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" -X POST -H "Content-Type: application/octet-stream" https://saucelabs.com/rest/v1/storage/automattic/Gutenberg.app.zip?overwrite=true --data-binary @./Gutenberg.app.zip
    - run:
        name: Run Device Tests
        command: |
          yarn device-tests

workflows:
  gutenberg-mobile:
    jobs:
      - checks:
          name: Check Correctness
          check-correctness: true
      - checks:
          name: Test iOS
          platform: ios
          check-tests: true
      - checks:
          name: Test Android
          platform: android
          check-tests: true
      - ios-device-checks:
          name: Test iOS on Device
      - android-device-checks:
          name: Test Android on Device
