on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          npm ci
          # It's not necessary to run the full build, since Jest can interpret
          # source files with `babel-jest`. Some packages have their own custom
          # build tasks, however. These must be run.
          npx lerna run build
          npm run test-unit:native -- --ci --maxWorkers=2 --cacheDirectory="$HOME/.jest-cache"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
