on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        arch: x86_64
        script: |
          npm ci
          # It's not necessary to run the full build, since Jest can interpret
          # source files with `babel-jest`. Some packages have their own custom
          # build tasks, however. These must be run.
          npx lerna run build
          mkdir -p test/native/screenshots
          npm run test-e2e:android:local
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: upload any screenshots
        path: test/native/screenshots
